# Generated by Django 5.1.3 on 2024-11-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_task_options_alter_task_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, '高'), (2, '中'), (3, '低')], default=2),
        ),
    ]
